//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seniorDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Table
    {
        public string CommentsAboutOrganization { get; set; }
        public string OrgName { get; set; }
        public Nullable<bool> Verified { get; set; }
        public int CommentID { get; set; }
        public int OrgID { get; set; }
    
        public virtual Main_Database_For_Directory Main_Database_For_Directory { get; set; }
    }
}
