//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seniorDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Database_For_Directory
    {
        public string Organization { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string StreetAddress { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string ServicesOffered { get; set; }
        public string TypeOfOrginization { get; set; }
        public byte[] InformationSource { get; set; }
        public byte[] ApprovedForDirectory { get; set; }
    }
}
